In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [18]:
b = np.array([[1,2,3],[1,2,3],[1,2,3]],dtype='int16')
print(b)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [4]:
c = np.array([1,2,3,4],ndmin=3)
print(c)

[[[1 2 3 4]]]


In [5]:
d = np.array([1,2,3,4],dtype=complex)
print(d)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [7]:
a.ndim

1

In [9]:
a.shape

(3,)

In [10]:
a.dtype

dtype('int32')

In [11]:
a.itemsize

4

In [12]:
a.size


3

In [13]:
a.itemsize*a.size

12

In [20]:
b.itemsize*b.size

18

In [21]:
#accessing rows and coulmns

In [32]:
arr = np.array([[1,2,3,4,5,6,7],
                [8,9,10,11,12,13,14]])

In [24]:
arr.ndim

2

In [25]:
arr.size

14

In [27]:
arr.itemsize * arr.size

56

In [28]:
arr[1,5]

13

In [29]:
arr[1,-2]

13

In [30]:
arr[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
arr[:,0]

array([1, 8])

In [36]:
arr[:,::2]

array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14]])

In [38]:
arr[1,5] =20
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [39]:
#three dimesnion array

In [6]:
arr1 =np.array([[[1,2,3],[1,2,3]],[[1,100,3],[1,2,3]]])
print(arr1)

[[[  1   2   3]
  [  1   2   3]]

 [[  1 100   3]
  [  1   2   3]]]


In [7]:
arr1[1][0][1]

100

In [ ]:
#intialinzing ways

In [12]:
np.zeros((2,3,1,3))

array([[[[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]]],


       [[[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]]]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.full((2,1),99)

array([[99],
       [99]])

In [21]:
np.random.rand(2,2,3)

array([[[0.00193367, 0.65849143, 0.80116589],
        [0.92930565, 0.14641029, 0.79383051]],

       [[0.24782147, 0.27465361, 0.72090837],
        [0.89666734, 0.04208975, 0.60213956]]])

In [23]:
np.random.randint(10,size=(3,3))

array([[0, 0, 9],
       [8, 8, 5],
       [2, 2, 6]])

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
a = np.ones((5,5))
print(a)

b = np.zeros((3,3))
print(b)
b[1][1] = 9
a[1:4,1:4] =  b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
a = np.array([12,3,4])
b = a.copy()
b

array([12,  3,  4])

In [44]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
b /a

array([5.        , 3.        , 2.33333333, 2.        ])

In [45]:
a + b

array([ 6,  8, 10, 12])

In [46]:
a - b

array([-4, -4, -4, -4])

In [47]:
a * b

array([ 5, 12, 21, 32])

In [48]:
a ** 2

array([ 1,  4,  9, 16])

In [54]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),3)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

In [56]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [58]:
stats = np.array([[1,2,3],[4,5,6]])

In [60]:
np.min(stats,axis = 1)

array([1, 4])

In [61]:
np.min(stats,axis = 0)

array([1, 2, 3])

In [62]:
np.max(stats)

6

In [63]:
np.sum(stats)

21

In [35]:

# Import Dependencies
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from time import sleep

driver = webdriver.Chrome()
driver.get("https://twitter.com/login")

subject = "Elon Musk"


# Setup the log in
sleep(3)
username = driver.find_element(By.XPATH,"//input[@name='text']")
username.send_keys("saim8877")
next_button = driver.find_element(By.XPATH,"//span[contains(text(),'Next')]")
next_button.click()

sleep(3)
password = driver.find_element(By.XPATH,"//input[@name='password']")
password.send_keys('Bigdog11@#')
log_in = driver.find_element(By.XPATH,"//span[contains(text(),'Log in')]")
log_in.click()

# Search item and fetch it
sleep(7)
search_box = driver.find_element(By.XPATH,"//input[@data-testid='SearchBox_Search_Input']")
search_box.send_keys(subject)
search_box.send_keys(Keys.ENTER)

sleep(7)
people = driver.find_element(By.XPATH,"//span[contains(text(),'People')]")
people.click()

sleep(10)
profile = driver.find_element(By.XPATH,"//*[@id='react-root']/div/div/div[2]/main/div/div/div/div/div/div[3]/section/div/div/div/div/div[1]/div/div/div/div/div[2]/div[1]/div[1]/div/div[1]/a/div/div[1]/span/span[1]")
profile.click()


UserTag = driver.find_element(By.XPATH,"//*[@id='id__qzqbo9e03o']").text
print(UserTag)
#TimeStamp = driver.find_element(By.XPATH,"//time").get_attribute('datetime')
Tweet = driver.find_element(By.XPATH,"//div[@data-testid='tweetText']").text
#Reply = driver.find_element(By.XPATH,"//div[@data-testid='reply']").text
#reTweet = driver.find_element(By.XPATH,"//div[@data-testid='retweet']").text
#Like = driver.find_element(By.XPATH,"//div[@data-testid='like']").text


UserTags=[]
TimeStamps=[]
Tweets=[]
Replys=[]
reTweets=[]
Likes=[]

articles = driver.find_elements(By.XPATH,"//article[@data-testid='tweet']")
while True:
    for article in articles:
        UserTag = driver.find_element(By.XPATH,".//div[@data-testid='User-Names']").text
        UserTags.append(UserTag)
        
        TimeStamp = driver.find_element(By.XPATH,".//time").get_attribute('datetime')
        TimeStamps.append(TimeStamp)
        
        Tweet = driver.find_element(By.XPATH,".//div[@data-testid='tweetText']").text
        Tweets.append(Tweet)
        
        Reply = driver.find_element(By.XPATH,".//div[@data-testid='reply']").text
        Replys.append(Reply)
        
        reTweet = driver.find_element(By.XPATH,".//div[@data-testid='retweet']").text
        reTweets.append(reTweet)
        
        Like = driver.find_element(By.XPATH,".//div[@data-testid='like']").text
        Likes.append(Like)
    driver.execute_script('window.scrollTo(0,document.body.scrollHeight);')
    sleep(3)
    articles = driver.find_elements(By.XPATH,"//article[@data-testid='tweet']")
    Tweets2 = list(set(Tweets))
    if len(Tweets2) > 5:
        break


print(len(UserTags),
len(TimeStamps),
len(Tweets),
len(Replys),
len(reTweets),
len(Likes))


import pandas as pd

df = pd.DataFrame(zip(UserTags,TimeStamps,Tweets,Replys,reTweets,Likes)
                  ,columns=['UserTags','TimeStamps','Tweets','Replys','reTweets','Likes'])

df.head()

df.to_excel(r"D:\Learnerea\Tables\tweets_live.xlsx",index=False)

import os
os.system('start "excel" "D:\Learnerea\Tables\\tweets_live.xlsx"')










NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='id__qzqbo9e03o']"}
  (Session info: chrome=114.0.5735.199); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00C5A813+48355]
	(No symbol) [0x00BEC4B1]
	(No symbol) [0x00AF5358]
	(No symbol) [0x00B209A5]
	(No symbol) [0x00B20B3B]
	(No symbol) [0x00B4E232]
	(No symbol) [0x00B3A784]
	(No symbol) [0x00B4C922]
	(No symbol) [0x00B3A536]
	(No symbol) [0x00B182DC]
	(No symbol) [0x00B193DD]
	GetHandleVerifier [0x00EBAABD+2539405]
	GetHandleVerifier [0x00EFA78F+2800735]
	GetHandleVerifier [0x00EF456C+2775612]
	GetHandleVerifier [0x00CE51E0+616112]
	(No symbol) [0x00BF5F8C]
	(No symbol) [0x00BF2328]
	(No symbol) [0x00BF240B]
	(No symbol) [0x00BE4FF7]
	BaseThreadInitThunk [0x76857D59+25]
	RtlInitializeExceptionChain [0x776EB79B+107]
	RtlClearBits [0x776EB71F+191]


In [11]:
pip install selenium

  Using cached selenium-4.10.0-py3-none-any.whl (6.7 MB)
  Using cached trio_websocket-0.10.3-py3-none-any.whl (17 kB)
  Using cached trio-0.22.2-py3-none-any.whl (400 kB)
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
  Using cached exceptiongroup-1.1.2-py3-none-any.whl (14 kB)
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
  Using cached outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
  Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)

