In [6]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.23.1
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

In [7]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [18]:
a = np.arange(start = 0,stop =10,step=2,dtype='int32')

In [19]:
print(a)

[0 2 4 6 8]


In [23]:
np.arange(100,109,2,'float32')

array([100., 102., 104., 106., 108.], dtype=float32)

In [28]:
b=np.arange(0,90,2)
for i in b:
    if i == 0:
        print("yes there is 0 element in given array")

yes there is 0 element in given array


In [30]:
print(np.all(a))

False


In [32]:
c = np.arange(11,100,2)
print(np.any(c))

True


In [35]:
d = np.array([True,False,True])
np.any(d)

True

In [41]:
e = np.array([[1,2,3,4],
              [3,np.nan,np.inf,2]])

In [42]:
print("Orignal array is : ",e)
print("Tested array  is : ",np.isfinite(e))

Orignal array is :  [[ 1.  2.  3.  4.]
 [ 3. nan inf  2.]]
Tested array  is :  [[ True  True  True  True]
 [ True False False  True]]


In [44]:
f = np.array([1,2,np.nan,3])

In [45]:
print(np.isnan(f))

[False False  True False]


In [54]:
g = np.array([1+1j,2,2.5,2333,2+9j,32.1])
print("Orignal array : ")
print(g)
print(np.iscomplex(g))
print(np.isreal(g))
print(np.isreal(g))
print(np.isscalar(g))

Orignal array : 
[1.000e+00+1.j 2.000e+00+0.j 2.500e+00+0.j 2.333e+03+0.j 2.000e+00+9.j
 3.210e+01+0.j]
[ True False False False  True False]
[False  True  True  True False  True]
[False  True  True  True False  True]
False


In [57]:
h = np.array([1,2,3,4,45,56,7,3,4,3])
i = np.array([7,5,4,6,7,9,8,4,4,2])
print(np.greater(h,i))
print(np.less(h,i))
print(np.less_equal(h,i))
print(np.greater_equal(h,i))

[False False False False  True  True False False False  True]
[ True  True  True  True False False  True  True False False]
[ True  True  True  True False False  True  True  True False]
[False False False False  True  True False False  True  True]


In [59]:
k = np.full((3,3),5)
k

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [64]:
k = np.ones(10)*5
k

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [68]:
j = np.arange(30,71,2)
print(j)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [3]:
l = np.random.normal(0,1,15)
print(l)

[ 1.08207886 -0.16984372 -0.76021636 -1.04557569  1.70732826 -0.68123661
  0.54368956  0.28435594 -0.10179743  0.64912846 -1.35413545  1.11774427
  1.08117626  0.80626972  0.65215366]


In [7]:
m = np.arange(0,12).reshape(3,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
a = np.array([4,7])
b = np.array([5,9])
print(np.dot(a,b))

83


In [9]:
a = np.array([4,7])
b = np.array([5,9])
print(np.add(a,b))

[ 9 16]


In [16]:
c = np.array([[1,2,3],[4,5,6],[6,5,4]])
d = np.array([1,0,1])
output = np.empty_like(c)
for i in range(3):
    output[i, : ] = c[i, :] + d
print(output)

[[2 2 4]
 [5 5 7]
 [7 5 5]]


In [19]:
print(c[0,1])

2
